name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip --no-cache-dir install --user setuptools wheel "urllib3==1.25.11"
          pip --no-cache-dir install --user -e .[tests,docs]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh

