name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip --no-cache-dir install setuptools wheel "urllib3==1.25.11"
          pip --no-cache-dir install -e .[tests,docs]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Build package
        run: |
          mkdir clean-build
          python setup.py sdist bdist_wheel --universal --dist-dir ./clean-build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          verify_metadata: false
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: clean-build/
